name: Lunes Stable KeepAlive

on:
  schedule:
    - cron: "0 1 */10 * *"
  workflow_dispatch:

jobs:
  login:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install -r requirements.txt

      - run: playwright install chromium

      - run: python login.py
        env:
          ACCOUNTS: ${{ secrets.ACCOUNTS }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          ONLY_ERROR_NOTIFY: ${{ secrets.ONLY_ERROR_NOTIFY }}

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cookies
          path: cookies/
